export const CHILDRENSSHOES = [
  {
    id: 0,
    name: "Nike Air Force 1 Low",
    image: "/img/Child Shoes Photos/ChildShoesPhotoOne.jpg",
    featured: true,
    description: "Girl's - black",
    price: "$70.00",
  },
  {
    id: 1,
    name: "Puma MB.02",
    image: "/img/Child Shoes Photos/ChildShoesPhotoTwo.jpg",
    featured: true,
    description: "Boys - white/blue",
    price: "$80.00",
  },
  {
    id: 2,
    name: "Jordan AJ 1 Low",
    image: "/img/Child Shoes Photos/ChildShoesPhotoThree.jpg",
    featured: true,
    description: "Boy's - black/white/red",
    price: "$90.00",
  },
  {
    id: 3,
    name: "UGG clasic II",
    image: "/img/Child Shoes Photos/ChildShoesPhotoFour.jpg",
    featured: true,
    description: "Girl's - red",
    price: "$60.00",
  },
  {
    id: 4,
    name: "Jordan Retro 3",
    image: "/img/Child Shoes Photos/ChildShoesPhotoFive.jpg",
    featured: true,
    description: "Boy's - black/white/red",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Nike Air Max 270",
    image: "/img/Child Shoes Photos/ChildShoesPhotoSix.jpg",
    featured: true,
    description: "Boy's - bright spruce/black/white",
    price: "$99.00",
  },
  {
    id: 6,
    name: "Nike Ja Morant One",
    image: "/img/Child Shoes Photos/ChildShoesPhotoSeven.jpg",
    featured: true,
    description: "Boys's - white/blue/yellow",
    price: "$90.00",
  },
  {
    id: 7,
    name: "New Balance 574 Core",
    image: "/img/Child Shoes Photos/ChildShoesPhotoEight.jpg",
    featured: true,
    description: "Boy's - black",
    price: "$70.00",
  },
  {
    id: 8,
    name: "Crocs Unlined Glitter",
    image: "/img/Child Shoes Photos/ChildShoesPhotoNine.jpg",
    featured: true,
    description: "Girl's - blue/pink",
    price: "$30.00",
  },
  {
    id: 9,
    name: "Nike Court Borough Mid 2",
    image: "/img/Child Shoes Photos/ChildShoesPhotoTen.jpg",
    featured: true,
    description: "Girl's - white/emerald rise",
    price: "$75.00",
  },
  {
    id: 10,
    name: "Van's Old Skool",
    image: "/img/Child Shoes Photos/ChildShoesPhotoEleven.jpg",
    featured: true,
    description: "Girl's - white/orange",
    price: "$50.00",
  },
  {
    id: 11,
    name: "On Cloud Sky",
    image: "/img/Child Shoes Photos/ChildShoesPhotoTwelve.jpg",
    featured: true,
    description: "Girl's - black/blue/white",
    price: "$110.00",
  },
];
