export const CLOTHING = [
  {
    id: 0,
    name: "Nike Sweat Shirt",
    image: "/img/Clothing Photos/ClothingOne.jpg",
    featured: true,
    description: "Men's - black",
    price: "$70.00",
  },
  {
    id: 1,
    name: "Adidas Track Pants",
    image: "/img/Clothing Photos/ClothingTwo.jpg",
    featured: true,
    description: "Women's - green/white",
    price: "$60.00",
  },
  {
    id: 2,
    name: "Nike Track Suit",
    image: "/img/Clothing Photos/ClothingThree.jpg",
    featured: true,
    description: "Boy's - black/grey",
    price: "$110.00",
  },
  {
    id: 3,
    name: "Sports Bra",
    image: "/img/Clothing Photos/ClothingFour.jpg",
    featured: true,
    description: "Women's - pink",
    price: "$60.00",
  },
  {
    id: 4,
    name: "Track Suit",
    image: "/img/Clothing Photos/ClothingFive.jpg",
    featured: true,
    description: "Women's plus - green/white",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Nike Air Max 270",
    image: "/img/Clothing Photos/ClothingSix.jpg",
    featured: true,
    description: "Boy's - bright spruce/black/white",
    price: "$99.00",
  },
  {
    id: 6,
    name: "Nike Ja Morant One",
    image: "/img/Clothing Photos/ClothingSeven.jpg",
    featured: true,
    description: "Boys's - white/blue/yellow",
    price: "$90.00",
  },
  {
    id: 7,
    name: "New Balance 574 Core",
    image: "/img/Clothing Photos/ClothingEight.jpg",
    featured: true,
    description: "Boy's - black",
    price: "$70.00",
  },
  {
    id: 8,
    name: "Crocs Unlined Glitter",
    image: "/img/Clothing Photos/ClothingNine.jpg",
    featured: true,
    description: "Girl's - blue/pink",
    price: "$30.00",
  },
  {
    id: 9,
    name: "Nike Court Borough Mid 2",
    image: "/img/Clothing Photos/ClothingTen.jpg",
    featured: true,
    description: "Girl's - white/emerald rise",
    price: "$75.00",
  },
  {
    id: 10,
    name: "Van's Old Skool",
    image: "/img/Clothing Photos/ClothingEleven.jpg",
    featured: true,
    description: "Girl's - white/orange",
    price: "$50.00",
  },
  {
    id: 11,
    name: "On Cloud Sky",
    image: "/img/Clothing Photos/ClothingTwelve.jpg",
    featured: true,
    description: "Girl's - black/blue/white",
    price: "$110.00",
  },
];
