export const CLOTHING = [
  {
    id: 0,
    name: "Nike Sweat Shirt",
    image: "/img/Clothing Photos/ClothingOne.jpg",
    featured: true,
    description: "Men's - black",
    price: "$70.00",
  },
  {
    id: 1,
    name: "Adidas Track Pants",
    image: "/img/Clothing Photos/ClothingTwo.jpg",
    featured: true,
    description: "Women's - green/white",
    price: "$60.00",
  },
  {
    id: 2,
    name: "Nike Track Suit",
    image: "/img/Clothing Photos/ClothingThree.jpg",
    featured: true,
    description: "Boy's - black/grey",
    price: "$110.00",
  },
  {
    id: 3,
    name: "Sports Bra",
    image: "/img/Clothing Photos/ClothingFour.jpg",
    featured: true,
    description: "Women's - pink",
    price: "$60.00",
  },
  {
    id: 4,
    name: "Track Suit",
    image: "/img/Clothing Photos/ClothingFive.jpg",
    featured: true,
    description: "Women's plus - green/white",
    price: "$120.00",
  },
  {
    id: 5,
    name: "Nike Air Max Shirt",
    image: "/img/Clothing Photos/ClothingSix.jpg",
    featured: true,
    description: "Mens's - bright spruce/black/white",
    price: "$99.00",
  },
  {
    id: 6,
    name: "Nike Shirt",
    image: "/img/Clothing Photos/ClothingSeven.jpg",
    featured: true,
    description: "Men's - black/red",
    price: "$40.00",
  },
  {
    id: 7,
    name: "Nike Air Sweat shirt",
    image: "/img/Clothing Photos/ClothingEight.jpg",
    featured: true,
    description: "Men's - black",
    price: "$70.00",
  },
  {
    id: 8,
    name: "White Coat",
    image: "/img/Clothing Photos/ClothingNine.jpg",
    featured: true,
    description: "Men's - white/grey/black",
    price: "$70.00",
  },
  {
    id: 9,
    name: "Nike Sweat Pants",
    image: "/img/Clothing Photos/ClothingTen.jpg",
    featured: true,
    description: "Men's - white/emerald rise",
    price: "$75.00",
  },
  {
    id: 10,
    name: "Adidas Sweat Pants",
    image: "/img/Clothing Photos/ClothingEleven.jpg",
    featured: true,
    description: "Women's - white/grey",
    price: "$770.00",
  },
  {
    id: 11,
    name: "New Balance Shirt",
    image: "/img/Clothing Photos/ClothingTwelve.jpg",
    featured: true,
    description: "Girl's - blue",
    price: "$30.00",
  },
];
