export const MENSSHOES = [
  {
    id: 0,
    name: "NIKE DUNK LOW",
    image: "/img/Mens Shoes Photos/MensPhotoOne.jpg",
    featured: true,
    description: "Men's - white/black/white",
    price: "$115.00",
  },
  {
    id: 1,
    name: "Nike Air Max '97",
    image: "/img/Mens Shoes Photos/MensPhotoTwo.jpg",
    featured: true,
    description: "Men's - white/black",
    price: "$175.00",
  },
  {
    id: 2,
    name: "New Balance 9060",
    image: "/img/Mens Shoes Photos/MensPhotoThree.jpg",
    featured: true,
    description: "Men's - black/grey",
    price: "$150.00",
  },
  {
    id: 3,
    name: "Adidas Original Campus 00's",
    image: "/img/Mens Shoes Photos/MensPhotoFour.jpg",
    description: "Men's - dark green/off white/white",
    featured: true,
    price: "$110.00",
  },
  {
    id: 4,
    name: "New Balance 9060",
    image: "/img/Mens Shoes Photos/MensPhotoFive.jpg",
    featured: true,
    description: "Men's - beige/grey/white",
    price: "$150.00",
  },
  {
    id: 5,
    name: "Jordan Retro 12",
    image: "/img/Mens Shoes Photos/MensPhotoSix.jpg",
    featured: true,
    description: "Men's - black/purple/gold",
    price: "$200.00",
  },
  {
    id: 6,
    name: "Nike Ja Morant One Fuel",
    image: "/img/Mens Shoes Photos/MensPhotoSeven.jpg",
    featured: true,
    description: "Men's - black/red/blue",
    price: "$110.00",
  },
  {
    id: 7,
    name: "Men's Balance 9060",
    image: "/img/Mens Shoes Photos/MensPhotoEight.jpg",
    featured: true,
    description: "Men's - green/white",
    price: "$150.00",
  },
  {
    id: 8,
    name: "Jordan AJ 1 MID SE V2",
    image: "/img/Mens Shoes Photos/MensPhotoNine.jpg",
    featured: true,
    description: "Men's - orange/red/black",
    price: "$135.00",
  },
  {
    id: 9,
    name: "Jordan MVP",
    image: "/img/Mens Shoes Photos/MensPhotoTen.jpg",
    featured: true,
    description: "Men's - blue/white/univeristy blue",
    price: "$165.00",
  },
  {
    id: 10,
    name: "Jordan's Retro 3",
    image: "/img/Mens Shoes Photos/MensPhotoEleven.jpg",
    featured: true,
    description: "Men's - tan/gold/tan",
    price: "$200.00",
  },
  {
    id: 11,
    name: "Jordan AJ Mid 1",
    image: "/img/Mens Shoes Photos/MensPhotoTwelve.jpg",
    featured: true,
    description: "Men's - lucky green/white/black",
    price: "$125.00",
  },
];
