export const MENSSHOES = [
  {
    id: 0,
    name: "NIKE DUNK LOW",
    image: "/img/Mens Shoes Photos/MensPhotoOne.jpg",
    featured: true,
    description: "Men's - white/black/white",
    price: "$115.00",
  },
  {
    id: 1,
    name: "Jordan Retro 11 Low IE",
    image: "/images/Mens Shoes Photos/MensPhotoTwo.jpg",
    featured: true,
    description: "Men's - white/black",
    price: "$185.00",
  },
  {
    id: 2,
    name: "New Balance 9060",
    image: "/images/Mens Shoes Photos/MensPhotoThree.jpg",
    featured: true,
    description: "Men's - black/grey",
    price: "$150.00",
  },
  {
    id: 3,
    name: "Adidas Original Campus 00's",
    image: "/images/Mens Shoes Photos/MensPhotoFour.jpg",
    description: "Men's - dark green/off white/white",
    featured: true,
    price: "$110.00",
  },
  {
    id: 4,
    name: "Nike Air Force 1 '07 LE",
    image: "/images/Mens Shoes Photos/MensPhotoFive.jpg",
    featured: true,
    description: "Men's - white/white",
    price: "$115.00",
  },
  {
    id: 5,
    name: "Jordan Retro 13",
    image: "/images/Mens Shoes Photos/MensPhotoSix.jpg",
    featured: true,
    description: "Men's - white/grey/red",
    price: "$200.00",
  },
  {
    id: 6,
    name: "Nike Ja Morant One Fuel",
    image: "/images/Mens Shoes Photos/MensPhotoSeven.jpg",
    featured: true,
    description: "Men's - black",
    price: "$110.00",
  },
  {
    id: 7,
    name: "Soft Fragrance",
    image: "/images/Mens Shoes Photos/MensPhotoEight.jpg",
    featured: true,
    description: "Soft body Fragrance that is enfused with essential oils.",
    price: "$20.00",
  },
  {
    id: 8,
    name: "Soft Fragrance",
    image: "/images/Mens Shoes Photos/MensPhotoNine.jpg",
    featured: true,
    description: "Soft body Fragrance that is enfused with essential oils.",
    price: "$20.00",
  },
  {
    id: 9,
    name: "New Balance 9060",
    image: "/images/Mens Shoes Photos/MensPhotoTen.jpg",
    featured: true,
    description: "Men's - grey/grey",
    price: "$150.00",
  },
  {
    id: 10,
    name: "Soft Fragrance",
    image: "/images/Mens Shoes Photos/MensPhotoEleven.jpg",
    featured: true,
    description: "Soft body Fragrance that is enfused with essential oils.",
    price: "$20.00",
  },
  {
    id: 11,
    name: "Soft Fragrance",
    image: "/images/Mens Shoes Photos/MensPhotoTwelve.jpg",
    featured: true,
    description: "Soft body Fragrance that is enfused with essential oils.",
    price: "$20.00",
  },
];
