export const WOMENSSHOES = [
  {
    id: 0,
    name: "Nike Dunk Low Next Nature",
    image: "/img/Womens Shoes Photos/WomensPhotoOne.jpg",
    featured: true,
    description: "Women's - hemp/sale",
    price: "$115.00",
  },
  {
    id: 1,
    name: "On Cloud",
    image: "/images/Womens Shoes Photos/WomensPhotoTwo.jpg",
    featured: true,
    description: "Women's - white/black",
    price: "$145.00",
  },
  {
    id: 2,
    name: "Adidas Originals Samba OG",
    image: "/images/Womens Shoes Photos/WomensPhotoThree.jpg",
    featured: true,
    description: "Women's - wonderclay/white",
    price: "$100.00",
  },
  {
    id: 3,
    name: "Nike Air Presto",
    image: "/images/Womens Shoes Photos/WomensPhotoFour.jpg",
    description: "Women's - white",
    featured: true,
    price: "$100.00",
  },
  {
    id: 4,
    name: "New Balance 9060",
    image: "/images/Womens Shoes Photos/WomensPhotoFive.jpg",
    featured: true,
    description: "Women's - beige/grey/white",
    price: "$150.00",
  },
  {
    id: 5,
    name: "Jordan Retro 12",
    image: "/images/Womens Shoes Photos/WomensPhotoSix.jpg",
    featured: true,
    description: "Women's - black/purple/gold",
    price: "$200.00",
  },
  {
    id: 6,
    name: "Nike Ja Morant One Fuel",
    image: "/images/Womens Shoes Photos/WomensPhotoSeven.jpg",
    featured: true,
    description: "Women's - black/red/blue",
    price: "$110.00",
  },
  {
    id: 7,
    name: "Men's Balance 9060",
    image: "/images/Womens Shoes Photos/WomensPhotoEight.jpg",
    featured: true,
    description: "Women's - green/white",
    price: "$150.00",
  },
  {
    id: 8,
    name: "Jordan AJ 1 MID SE V2",
    image: "/images/Womens Shoes Photos/WomensPhotoNine.jpg",
    featured: true,
    description: "Women's - orange/red/black",
    price: "$135.00",
  },
  {
    id: 9,
    name: "Jordan MVP",
    image: "/images/Womens Shoes Photos/WomensPhotoTen.jpg",
    featured: true,
    description: "Women's - blue/white/univeristy blue",
    price: "$165.00",
  },
  {
    id: 10,
    name: "Jordan's Retro 3",
    image: "/images/Womens Shoes Photos/WomensPhotoEleven.jpg",
    featured: true,
    description: "Women's - tan/gold/tan",
    price: "$200.00",
  },
  {
    id: 11,
    name: "Jordan AJ Mid 1",
    image: "/images/Womens Shoes Photos/WomensPhotoTwelve.jpg",
    featured: true,
    description: "Women's - lucky green/white/black",
    price: "$125.00",
  },
];
