export const WOMENSSHOES = [
  {
    id: 0,
    name: "Nike Dunk Low Next Nature",
    image: "/img/Womens Shoes Photos/WomensPhotoOne.jpg",
    featured: true,
    description: "Women's - hemp/sale",
    price: "$115.00",
  },
  {
    id: 1,
    name: "On Cloud",
    image: "/img/Womens Shoes Photos/WomensPhotoTwo.jpg",
    featured: true,
    description: "Women's - white/black",
    price: "$145.00",
  },
  {
    id: 2,
    name: "Adidas Originals Samba OG",
    image: "/img/Womens Shoes Photos/WomensPhotoThree.jpg",
    featured: true,
    description: "Women's - wonderclay/white",
    price: "$100.00",
  },
  {
    id: 3,
    name: "Nike Air Presto",
    image: "/img/Womens Shoes Photos/WomensPhotoFour.jpg",
    description: "Women's - white",
    featured: true,
    price: "$100.00",
  },
  {
    id: 4,
    name: "Jordan Air Elevate Low",
    image: "/img/Womens Shoes Photos/WomensPhotoFive.jpg",
    featured: true,
    description: "Women's - gold/black/white",
    price: "$135.00",
  },
  {
    id: 5,
    name: "UGG Taz",
    image: "/img/Womens Shoes Photos/WomensPhotoSix.jpg",
    featured: true,
    description: "Women's - beige",
    price: "$130.00",
  },
  {
    id: 6,
    name: "On Cloudmonster",
    image: "/img/Womens Shoes Photos/WomensPhotoSeven.jpg",
    featured: true,
    description: "Women's - meadow/glacier",
    price: "$170.00",
  },
  {
    id: 7,
    name: "New Balance 550",
    image: "/img/Womens Shoes Photos/WomensPhotoEight.jpg",
    featured: true,
    description: "Women's - white/red/pink",
    price: "$120.00",
  },
  {
    id: 8,
    name: "Adidas Ultraboost DNA",
    image: "/img/Womens Shoes Photos/WomensPhotoNine.jpg",
    featured: true,
    description: "Women's - white/white",
    price: "$130.00",
  },
  {
    id: 9,
    name: "Adidas Originals NMD",
    image: "/img/Womens Shoes Photos/WomensPhotoTen.jpg",
    featured: true,
    description: "Women's - maroon",
    price: "$90.00",
  },
  {
    id: 10,
    name: "Converse Chuck Taylor Allstars",
    image: "/img/Womens Shoes Photos/WomensPhotoEleven.jpg",
    featured: true,
    description: "Women's - peach",
    price: "$40.00",
  },
  {
    id: 11,
    name: "Nike Air Max Bliss",
    image: "/img/Womens Shoes Photos/WomensPhotoTwelve.jpg",
    featured: true,
    description: "Women's - white/submit white",
    price: "$75.00",
  },
];
